export const FETCHED_TOP_STORIES = "FETCHED_TOP_STORIES";
export const FETCHED_SEARCH = "FETCHED_SEARCH";
export const FETCHED_NEW_PAGE = "FETCHED_NEW_PAGE";
export const ADDED_TO_BOOKMARKS = "ADDED_TO_BOOKMARKS";
export const REMOVED_FROM_BOOKMARKS = "REMOVED_FROM_BOOKMARKS";
export const UPDATE_LOADING = "UPDATE_LOADING";
